version: '3.7'

services:
  domain:
    image: todomvc/domain:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Domain/Dockerfile
    depends_on:
      - rabbitmq
      - eventstore
    restart: always
  application:
    image: todomvc/application:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Application/Dockerfile
    depends_on:
      - rabbitmq
      - eventstore
    restart: always
  presentation:
    image: todomvc/web:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8080:80"
      - "4443:443"
    restart: always
  
  # windows image
  #rabbitmq:
  #  image: spring2/rabbitmq
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"

  # linux images
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=TRUE
      - EVENTSTORE_RUN_PROJECTIONS=ALL
    ports:
      - "1113:1113"
      - "2113:2113"
